-- DEPRECATED: This file has been superseded by 003_integrated_schema.sql
-- 
-- The new integrated schema combines:
-- 1. Production-proven schema (5,582 real products)
-- 2. Modern design improvements 
-- 3. Backward compatibility
--
-- Please use 003_integrated_schema.sql instead.
--
-- Reasons for change:
-- - Leverages existing production database structure
-- - Maintains compatibility with existing 5,582 products
-- - Optimizes performance with proven field types
-- - Adds modern enhancements without breaking changes

-- Redirect to new migration
-- See: 003_integrated_schema.sql

-- DEPRECATED: This file has been superseded by 003_integrated_schema.sql
-- 
-- The new integrated schema combines:
-- 1. Production-proven schema (5,582 real products)
-- 2. Modern design improvements 
-- 3. Backward compatibility
--
-- Please use 003_integrated_schema.sql instead.
--
-- Reasons for change:
-- - Leverages existing production database structure
-- - Maintains compatibility with existing 5,582 products
-- - Optimizes performance with proven field types
-- - Adds modern enhancements without breaking changes

-- Redirect to new migration
-- See: 003_integrated_schema.sql
