# Cargo 기본 설정 (안정적 테스트 우선)
[build]
# 병렬 빌드 (합리적 기본값)
jobs = 8

# 개발/테스트에 안전한 기본 환경값
[env]
# 캐시/커스텀 링커 비활성화: 일부 크레이트(lld, objc2, ring)와 충돌 방지
# 필요 시 로컬에서만 export RUSTC_WRAPPER=sccache 로 활성화하세요.
# RUSTC_WRAPPER = "sccache"

# 테스트 시에는 incremental 켜서 반복 빌드 속도 개선
CARGO_INCREMENTAL = "1"
RUST_BACKTRACE = "0"
CARGO_BUILD_JOBS = "8"
CARGO_NET_RETRY = "3"
CARGO_TARGET_DIR = "target"
# 명시적 링커 지정은 유지(기본 clang)하되, 추가 link-arg 최적화는 해제
CARGO_TARGET_X86_64_APPLE_DARWIN_LINKER = "clang"
CARGO_TARGET_AARCH64_APPLE_DARWIN_LINKER = "clang"

# 타겟별 rustflags: 커스텀 링커/플래그 제거(기본 시스템 링커 사용)
[target.x86_64-apple-darwin]
rustflags = [
    "-C", "target-cpu=native"
]

[target.aarch64-apple-darwin]
rustflags = [
    "-C", "target-cpu=native"
]

# 네트워크 설정
[net]
git-fetch-with-cli = true
