// Structured crawl event discriminated union (schema v1)
// Autogenerated prototype (manual for now). Later: derive from Rust via codegen.

export const CRAWL_EVENT_SCHEMA_VERSION = 1 as const;

export type CrawlEvent =
  | CrawlSessionStarted
  | CrawlSessionCompleted
  | CrawlSessionFailed
  | StageStarted
  | StageProgress
  | StageItemStarted
  | StageItemCompleted
  | StageItemFailed
  | StageItemRetrying
  | OverallProgressUpdate
  | ListPageBatchStarted
  | ListPageProgress
  | ListPageBatchCompleted;

export type EventType = CrawlEvent['event_type'];

interface BaseEvent {
  event_type: string; // discriminant
  event_id: string;
  schema_version: number;
  sequence: number;
  timestamp: string; // ISO8601
  session_id: string;
  message?: string;
}

export interface CrawlSessionStarted extends BaseEvent {
  event_type: 'CrawlSessionStarted';
  total_stages?: number;
}
export interface CrawlSessionCompleted extends BaseEvent {
  event_type: 'CrawlSessionCompleted';
  total_duration_ms?: number;
  successful_items_count?: number;
  failed_items_count?: number;
}
export interface CrawlSessionFailed extends BaseEvent {
  event_type: 'CrawlSessionFailed';
  error_code?: string;
  error_category?: string;
  error_message: string;
  retriable?: boolean;
}
export interface StageStarted extends BaseEvent {
  event_type: 'StageStarted';
  batch_id?: string;
  stage_name: string;
  stage_index: number;
  total_items_in_stage?: number;
}
export interface StageProgress extends BaseEvent {
  event_type: 'StageProgress';
  batch_id?: string;
  stage_name: string;
  stage_index: number;
  current_item_index?: number;
  total_items_in_stage?: number;
  progress_percentage?: number; // 0-100
}
export interface StageItemStarted extends BaseEvent {
  event_type: 'StageItemStarted';
  batch_id?: string;
  stage_name: string;
  item_id: string;
}
export interface StageItemCompleted extends BaseEvent {
  event_type: 'StageItemCompleted';
  batch_id?: string;
  stage_name: string;
  item_id: string;
  duration_ms?: number;
}
export interface StageItemFailed extends BaseEvent {
  event_type: 'StageItemFailed';
  batch_id?: string;
  stage_name: string;
  item_id: string;
  error_code?: string;
  error_category?: string;
  error_message: string;
  retry_possible?: boolean;
}
export interface StageItemRetrying extends BaseEvent {
  event_type: 'StageItemRetrying';
  batch_id?: string;
  stage_name: string;
  item_id: string;
  retry_attempt: number;
  max_retries?: number;
  reason?: string;
}
export interface OverallProgressUpdate extends BaseEvent {
  event_type: 'OverallProgressUpdate';
  current_stage_index?: number;
  total_stages?: number;
  overall_progress_percentage?: number;
  completed_items_count?: number;
  total_items_count?: number;
}

// === ListPageCrawling 진행상황 이벤트 ===
export interface ListPageBatchStarted extends BaseEvent {
  event_type: 'ListPageBatchStarted';
  batch_id: string;
  total_pages: number;
  page_numbers: number[]; // 물리 페이지 번호 목록
}

export interface ListPageProgress extends BaseEvent {
  event_type: 'ListPageProgress';
  batch_id: string;
  page_number: number;
  page_id: string;
  collected_urls: number;
  expected_urls: number;
  status: 'success' | 'partial' | 'failed';
  retry_count: number;
  error?: string;
}

export interface ListPageBatchCompleted extends BaseEvent {
  event_type: 'ListPageBatchCompleted';
  batch_id: string;
  total_pages: number;
  successful_pages: number;
  partial_pages: number;
  failed_pages: number;
  total_urls_collected: number;
  duration_ms: number;
}

// Type guard helper
export function isCrawlEvent(value: any): value is CrawlEvent {
  return value && typeof value === 'object' && typeof value.event_type === 'string' && typeof value.event_id === 'string';
}
