# rMatterCertis 기본 설정
# 모든 환경에서 공통으로 사용되는 기본값들

[system]
max_concurrent_sessions = 10
session_timeout_secs = 3600  # 1시간
stage_timeout_secs = 300     # 5분
cancellation_timeout_secs = 30
memory_limit_mb = 2048
abort_on_database_error = false
abort_on_validation_error = false

[retry_policies.list_collection]
max_attempts = 3
base_delay_ms = 1000
max_delay_ms = 30000
backoff_multiplier = 2.0
jitter_range_ms = 500
retry_on_errors = [
    "NetworkTimeout",
    { ServerError = { status_range = [500, 599] } },
    "RateLimit"
]

[retry_policies.detail_collection]
max_attempts = 5
base_delay_ms = 500
max_delay_ms = 60000
backoff_multiplier = 1.5
jitter_range_ms = 200
retry_on_errors = [
    "NetworkTimeout",
    { ServerError = { status_range = [500, 599] } },
    "ParseError"
]

[retry_policies.data_validation]
max_attempts = 2
base_delay_ms = 100
max_delay_ms = 5000
backoff_multiplier = 1.2
jitter_range_ms = 50
retry_on_errors = [
    "ValidationTimeout"
]

[retry_policies.database_save]
max_attempts = 10
base_delay_ms = 200
max_delay_ms = 30000

[actor]
session_timeout_secs = 300
batch_timeout_secs = 600
stage_timeout_secs = 120
max_concurrent_sessions = 10
max_concurrent_batches = 3
backoff_multiplier = 1.8
jitter_range_ms = 100
retry_on_errors = [
    "DatabaseConnection",
    "DatabaseTimeout",
    "DatabaseLock"
]

[performance.batch_sizes]
initial_size = 10
min_size = 1
max_size = 100
auto_adjust_threshold = 0.8
adjust_multiplier = 1.5

[performance.concurrency]
max_concurrent_tasks = 50
task_queue_size = 1000

[performance.concurrency.stage_concurrency_limits]
list_collection = 5
detail_collection = 20
data_validation = 10
database_save = 3
batch_processing = 10

[performance.buffers]
request_buffer_size = 10000
response_buffer_size = 10000
temp_storage_limit_mb = 500

[channels]
control_buffer_size = 100
event_buffer_size = 1000
backpressure_threshold = 0.8

metrics_interval_secs = 30
log_level = "INFO"
enable_profiling = false
event_retention_days = 7

[actor]
session_timeout_secs = 300
batch_timeout_secs = 600
stage_timeout_secs = 120
max_concurrent_sessions = 10
max_concurrent_batches = 3
