# 개발 환경 설정
# 빠른 피드백과 디버깅을 위한 최적화

[system]
max_concurrent_sessions = 5
session_timeout_secs = 1800  # 30분 (개발 시 짧게)
stage_timeout_secs = 120     # 2분 (빠른 실패)
memory_limit_mb = 1024       # 개발 환경에서는 메모리 절약

[retry_policies.list_collection]
max_attempts = 2             # 개발 시 빠른 실패
base_delay_ms = 500
max_delay_ms = 5000          # 짧은 대기

[retry_policies.detail_collection]
max_attempts = 3
base_delay_ms = 200
max_delay_ms = 10000

[performance.batch_sizes]
initial_size = 5             # 작은 배치로 빠른 테스트
min_size = 1
max_size = 20                # 개발 환경에서는 작게

[performance.concurrency]
max_concurrent_tasks = 20    # 개발 머신 고려
task_queue_size = 500

[performance.concurrency.stage_concurrency_limits]
list_collection = 2
detail_collection = 5
data_validation = 3
database_save = 1
batch_processing = 3

[channels]
control_buffer_size = 50     # 작은 버퍼
event_buffer_size = 200
backpressure_threshold = 0.7

[monitoring]
metrics_interval_secs = 10
log_level = "DEBUG"
enable_profiling = true
event_retention_days = 3

[actor]
session_timeout_secs = 1800  # 30분 (개발환경)
stage_timeout_secs = 120     # 2분 (빠른 피드백)
batch_timeout_secs = 900     # 15분
max_concurrent_sessions = 5   # 개발환경에서 제한
max_concurrent_batches = 20
