# 운영 환경 설정
# 안정성과 성능을 위한 최적화

[system]
max_concurrent_sessions = 50
session_timeout_secs = 7200  # 2시간 (충분한 시간)
stage_timeout_secs = 600     # 10분 (여유있게)
cancellation_timeout_secs = 60
memory_limit_mb = 8192       # 충분한 메모리
abort_on_database_error = true  # 운영에서는 DB 오류 시 중단

[retry_policies.list_collection]
max_attempts = 5             # 운영에서는 재시도 많이
base_delay_ms = 2000
max_delay_ms = 120000        # 2분까지 대기
backoff_multiplier = 2.5
jitter_range_ms = 1000

[retry_policies.detail_collection]
max_attempts = 8
base_delay_ms = 1000
max_delay_ms = 300000        # 5분까지 대기
backoff_multiplier = 2.0
jitter_range_ms = 500

[retry_policies.database_save]
max_attempts = 15            # DB 저장은 많이 재시도
base_delay_ms = 500
max_delay_ms = 60000
backoff_multiplier = 1.5

[performance.batch_sizes]
initial_size = 50            # 큰 배치로 효율성
min_size = 10
max_size = 500               # 운영에서는 크게
auto_adjust_threshold = 0.9
adjust_multiplier = 1.3

[performance.concurrency]
max_concurrent_tasks = 200   # 높은 동시성
task_queue_size = 5000

[performance.concurrency.stage_concurrency_limits]
list_collection = 20
detail_collection = 80
data_validation = 40
database_save = 10
batch_processing = 50

[performance.buffers]
request_buffer_size = 50000  # 큰 버퍼
response_buffer_size = 50000
temp_storage_limit_mb = 2048

[channels]
control_buffer_size = 500
event_buffer_size = 5000
backpressure_threshold = 0.85

[monitoring]
metrics_interval_secs = 60
log_level = "WARN"
enable_profiling = false
event_retention_days = 30

[actor]
session_timeout_secs = 7200  # 2시간 (프로덕션)
stage_timeout_secs = 600     # 10분 (안정성 우선)
batch_timeout_secs = 3600    # 1시간
max_concurrent_sessions = 20  # 높은 처리량
max_concurrent_batches = 100
